### ISSUE TITLE
Txdone interrupt

### ISSUE THREAD

**Issue by simon88** [MartiGeek17/LoRa-RFM95-STM32#3]
Hi,
Don't know if the project is always alive, but I have an issue when I'm trying to wait tx done, `reg_read = RF95_read(RH_RF95_REG_12_IRQ_FLAGS);`in `RF95_Check_TxDone`is always 0, but my message is send and I receive it with receiver

**Comment by MartiGeek17** [comment]
I have uploaded a sample code about how I used it, it was long time ago but maybe it helps you.

**Comment by simon88** [comment]
Perfect
